#!/usr/bin/env bash

# Get the currently active tag
tag=$(herbstclient attr tags.focus.name)

# Redirect to dmenu_path if available
selectedPath=$(dmenu_path | rofi -show run "$@")

#cache=${XDG_CACHE_HOME:-"$HOME/.cache"}
#selectedPath=$(dmenu "$@" < "$cache")

# Move next window from this process to this tag. Prepend the rule so
# that it may be overwritten by existing custom rules e.g. in the
# autostart. Also set a maximum age for this rule of 120 seconds and
# mark it as one-time-only rule.
herbstclient rule prepend maxage="120" pid="$$" tag="$tag" once

exec $selectedPath
